version: "3"
services:
  py_webs:
#    restart: "no"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: py_webs
    command: tail -f /dev/null
    volumes:
      - vol_pywebs:/var/vol_pywebs
    labels:
      deck-chores.qjob.command: python3 main.py -t2
      deck-chores.qjob.interval: 30s
      deck-chores.rjob.command: python3 main.py -t1
      deck-chores.rjob.interval: 100s
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  vol_pywebs:
    external: true
